# Generated by Django 4.2.5 on 2023-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(upload_to='skills')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_type', models.CharField(choices=[('Frontend', 'Frontend'), ('backend', 'backend'), ('devops', 'Devops'), ('API_development', 'API_Development')], max_length=255)),
            ],
        ),
    ]
