# Generated by Django 4.2.5 on 2023-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='skills'),
        ),
    ]
