# Generated by Django 4.2.5 on 2023-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_skill_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'backend'), ('devops', 'Devops'), ('API_development', 'API_Development')], max_length=255),
        ),
    ]
