# Generated by Django 4.2.5 on 2023-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'Devops'), ('API_development', 'API_Development')], max_length=255),
        ),
    ]
